"""Convert a wandb run config into a coalesced_baseline YAML config.

Use it to turn an HPO sweep winner into a reusable config file — e.g. to rerun
the selected config across several seeds for the negated-literal ablation.

Source may be either:
  * a wandb run: an entity/project/run_id path or a full run URL, or
  * a JSON file: either wandb's raw `config.json` ({"key": {"value": v}}) or an
    already-flat {"key": v} dump (like the one pasted from the run's Overview).

The `seed` in the emitted config can be overridden on the CLI at run time
(`coalesced_baseline.py --seed N`), so a single converted config drives every
seed replica.
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

import yaml

# Keys grouped into the sections used by configs/coalesced_baseline/*.yml. The
# loader (coalesced_baseline.load_config) flattens all sections, so grouping is
# purely cosmetic — but keeping the familiar layout makes the output diffable
# against the hand-written configs. Order within each list is the emit order.
SECTIONS: dict[str, list[str]] = {
    "model": [
        "clauses",
        "T",
        "s",
        "max_included_literals",
        "feature_negation",
        "platform",
        "output_balancing",
        "type_iii_feedback",
        "max_positive_clauses",
        "mask_target_literal_p",
        "clause_drop_p",
        "type_i_ii_ratio",
    ],
    "data": [
        "dataset",
        "rating_threshold",
        "k_core",
        "unit",
        "val_ratio",
        "max_per_user",
        "input_subsample_t",
        "subsample_mode",
        "max_classes",
    ],
    "training": ["epochs", "seed"],
    "runtime": ["device_id"],
    "logging": ["wandb_project"],
}

# wandb bookkeeping / logger-injected keys that are not coalesced_baseline args.
# `dataset_name` is the logger's copy of the dataset; the real arg is `dataset`
# (remapped below), so drop the copy here.
_DROP_KEYS = {"dataset_name"}


def unwrap_config(raw: dict) -> dict:
    """Flatten wandb's `{key: {"value": v}}` nesting; pass flat dicts through.

    Drops private wandb keys (leading underscore, e.g. `_wandb`, `_step`).
    """
    out = {}
    for k, v in raw.items():
        if k.startswith("_"):
            continue
        out[k] = v["value"] if isinstance(v, dict) and set(v) == {"value"} else v
    return out


def normalise(cfg: dict) -> dict:
    """Map wandb config keys onto coalesced_baseline arg names."""
    cfg = dict(cfg)
    # `dataset_name` -> `dataset`. Omit it for the default movielens1m so the
    # emitted config matches the hand-written MovieLens configs (which leave
    # `dataset` unset); keep it for any other dataset (e.g. vibrent).
    ds = cfg.pop("dataset_name", None)
    if ds is not None and ds != "movielens1m" and "dataset" not in cfg:
        cfg["dataset"] = ds
    for k in _DROP_KEYS:
        cfg.pop(k, None)
    return cfg


def to_sections(cfg: dict) -> dict[str, dict]:
    """Route flat config keys into the named YAML sections.

    Keys not recognised by any section are collected into a trailing `extra`
    section (still loaded, since load_config flattens everything) and reported
    on stderr so nothing is silently dropped.
    """
    routed: dict[str, dict] = {}
    seen: set[str] = set()
    for section, keys in SECTIONS.items():
        body = {k: cfg[k] for k in keys if k in cfg}
        if body:
            routed[section] = body
            seen.update(body)
    extra = {k: v for k, v in cfg.items() if k not in seen}
    if extra:
        print(
            f"warning: {len(extra)} unmapped key(s) placed under `extra`: "
            f"{sorted(extra)}",
            file=sys.stderr,
        )
        routed["extra"] = extra
    return routed


def render(sections: dict[str, dict], provenance: str) -> str:
    """Serialise sections to YAML with a provenance header and section spacing."""
    header = (
        f"# Generated by experiments/wandb_config_to_yaml.py on "
        f"{datetime.now():%Y-%m-%d %H:%M}\n"
        f"# Source: {provenance}\n"
        f"# Run: python experiments/coalesced_baseline.py --config <this file> [--seed N]\n\n"
    )
    blocks = [
        yaml.safe_dump({name: body}, sort_keys=False, default_flow_style=False)
        for name, body in sections.items()
    ]
    return header + "\n".join(blocks)


_RUN_URL = re.compile(
    r"(?:wandb\.ai/)?(?P<entity>[^/]+)/(?P<project>[^/]+)/runs?/(?P<id>[^/?#]+)"
)
_RUN_PATH = re.compile(r"^(?P<entity>[^/]+)/(?P<project>[^/]+)/(?P<id>[^/?#]+)$")


def load_source(source: str) -> tuple[dict, str]:
    """Return (flat_config, provenance) from a JSON file or a wandb run ref."""
    p = Path(source)
    if p.is_file():
        with open(p) as f:
            raw = json.load(f)
        return unwrap_config(raw), f"file {p}"

    m = _RUN_URL.search(source) or _RUN_PATH.match(source)
    if not m:
        raise SystemExit(
            f"Source {source!r} is neither an existing JSON file nor an "
            "entity/project/run_id path or wandb run URL."
        )
    import wandb

    run_path = f"{m['entity']}/{m['project']}/{m['id']}"
    run = wandb.Api(timeout=60).run(run_path)
    # run.config is already flat ({key: value}); unwrap is a no-op safeguard.
    return unwrap_config(dict(run.config)), f"wandb run {run_path} ({run.name})"


def main(argv=None) -> None:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("source", help="wandb run path/URL, or a path to a config JSON file")
    p.add_argument(
        "-o",
        "--out",
        type=Path,
        default=None,
        help="Output .yml path (default: stdout)",
    )
    p.add_argument(
        "--seed", type=int, default=None, help="Override the seed in the emitted config"
    )
    args = p.parse_args(argv)

    flat, provenance = load_source(args.source)
    cfg = normalise(flat)
    if args.seed is not None:
        cfg["seed"] = args.seed

    text = render(to_sections(cfg), provenance)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8")
        print(f"Wrote {args.out}")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
